In [1]:
import torch
import numpy as np
import svox2
import svox2_my

import matplotlib.pyplot as plt

/home/mshe/workspace/omv_src/svox2/svox2/utils.py:39: UserWarning: CUDA extension svox2.csrc could not be loaded! Operations will be slow.
Please do not import svox in the svox2 source directory.
  warn("CUDA extension svox2.csrc could not be loaded! " +


In [2]:
grid = svox2.SparseGrid(256, radius = [1., 1., 1.], center = [0., 0. ,0.], device='cpu')
grid_my = svox2_my.SparseGrid(256, radius=[1., 1., 1.], center=[0., 0., 0], device='cpu')

In [3]:
print(f'radius same? {grid.radius == grid_my.radius}')
print(f'center same? {grid.center == grid_my.center}')
print(f'_offset same? {grid._offset == grid_my._offset}')
print(f'_scaling same? {grid._scaling == grid_my._scaling}')
print(f'density data same? {torch.all(grid.density_data == grid_my.density_data)}')
print(f'links data: {torch.all(grid.links == grid_my.links)}')
print(f'sh data: {torch.all(grid.sh_data == grid_my.sh_data)}')

radius same? tensor([True, True, True])
center same? tensor([True, True, True])
_offset same? tensor([True, True, True])
_scaling same? tensor([True, True, True])
density data same? True
links data: True
sh data: True


In [4]:
# Now, test the load function
path = "/home/mshe/workspace/omv_src/svox2/opt/ckpt/lego-debug/ckpt.npz"
path = "/home/mshe/workspace/omv_src/svox2/opt/ckpt/lego-debug/ckpt.npz"
grid = svox2.SparseGrid.load(path)
grid_my = svox2_my.SparseGrid.load(path)

In [5]:
print(f'radius same? {grid.radius == grid_my.radius}')
print(f'center same? {grid.center == grid_my.center}')
print(f'_offset same? {grid._offset == grid_my._offset}')
print(f'_scaling same? {grid._scaling == grid_my._scaling}')
print(f'density data same? {torch.all(grid.density_data == grid_my.density_data)}')
print(f'links data: {torch.all(grid.links == grid_my.links)}')
print(f'sh data: {torch.all(grid.sh_data == grid_my.sh_data)}')

radius same? tensor([True, True, True])
center same? tensor([True, True, True])
_offset same? tensor([True, True, True])
_scaling same? tensor([True, True, True])
density data same? True
links data: True
sh data: True


In [6]:
radius = torch.tensor([10., 10., 10.])
center = torch.tensor([0.0, 0.0, 0.0])
offset = 0.5 * (1. - center / radius)
scale = 0.5 / radius

print(f'offset: {offset}, scale: {scale}')


offset: tensor([0.5000, 0.5000, 0.5000]), scale: tensor([0.0500, 0.0500, 0.0500])


In [7]:
point = torch.tensor([0.0, 0.0, 0.0]).unsqueeze(0)
grid.world2grid(point), grid_my.world2grid(point)

(tensor([[255.5000, 255.5000, 255.5000]]),
 tensor([[255.5000, 255.5000, 255.5000]]))

In [8]:
sample_sigma, sample_rgb = grid.sample(point)
sample_sigma_my, sample_rgb_my = grid_my.sample(point)
torch.allclose(sample_sigma, sample_sigma_my), torch.allclose(sample_sigma_my, sample_rgb_my)

(True, True)

In [18]:
# plot density data
gsz = grid._grid_size()

X = torch.arange(gsz[0], dtype=torch.float32) - 0.5
Y = torch.arange(gsz[1], dtype=torch.float32) - 0.5
Z = torch.arange(gsz[2], dtype=torch.float32) - 0.5
X, Y, Z = torch.meshgrid(X, Y, Z)
Z.shape, grid.density_data.shape

(torch.Size([512, 512, 512]), torch.Size([5386342, 1]))

In [22]:
point = torch.tensor([-0.3, 10.0, 8.2]).unsqueeze(0)
point.clamp_min_(0.0)

tensor([[ 0.0000, 10.0000,  8.2000]])